import { describe, expect, it } from 'vitest'
import { mount } from '@vue/test-utils'
import ScaleSelector from '@/components/common/ScaleSelector.vue'

// The element that carries the grid class is, by construction, the buttons' parent.
function buttonRowClasses(wrapper: ReturnType<typeof mount>): string {
  return (wrapper.find('button').element.parentElement as HTMLElement).className
}

describe('ScaleSelector', () => {
  it('renders 1 through 10 by default', () => {
    const wrapper = mount(ScaleSelector, { props: { modelValue: null } })

    const labels = wrapper.findAll('button').map((b) => b.text())
    expect(labels).toEqual(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])

    wrapper.unmount()
  })

  it('renders 1 through 5 when max is 5', () => {
    const wrapper = mount(ScaleSelector, { props: { modelValue: null, max: 5 } })

    const labels = wrapper.findAll('button').map((b) => b.text())
    expect(labels).toEqual(['1', '2', '3', '4', '5'])

    wrapper.unmount()
  })

  // The Tailwind guard: an interpolated `grid-cols-${max}` would never be generated by the
  // scanner and the grid would silently collapse to one column.
  it('uses a literal grid-cols-10 class by default', () => {
    const wrapper = mount(ScaleSelector, { props: { modelValue: null } })

    expect(buttonRowClasses(wrapper)).toContain('grid-cols-10')

    wrapper.unmount()
  })

  it('uses a literal grid-cols-5 class when max is 5', () => {
    const wrapper = mount(ScaleSelector, { props: { modelValue: null, max: 5 } })

    expect(buttonRowClasses(wrapper)).toContain('grid-cols-5')

    wrapper.unmount()
  })

  it('emits the tapped value', async () => {
    const wrapper = mount(ScaleSelector, { props: { modelValue: null } })

    const three = wrapper.findAll('button').find((b) => b.text() === '3')
    await three!.trigger('click')

    expect(wrapper.emitted('update:modelValue')).toEqual([[3]])

    wrapper.unmount()
  })

  it('marks the selected value as pressed', () => {
    const wrapper = mount(ScaleSelector, { props: { modelValue: 4 } })

    const pressed = wrapper.findAll('button[aria-pressed="true"]')
    expect(pressed).toHaveLength(1)
    expect(pressed[0].text()).toBe('4')

    wrapper.unmount()
  })

  it('renders no label row when labels is null, and the three labels when provided', () => {
    const bare = mount(ScaleSelector, { props: { modelValue: null } })
    expect(bare.text()).not.toContain('Easy')
    expect(bare.text()).not.toContain('Steady')
    expect(bare.text()).not.toContain('Max')
    bare.unmount()

    const labelled = mount(ScaleSelector, {
      props: { modelValue: null, max: 5, labels: ['Poor', 'OK', 'Great'] },
    })
    expect(labelled.text()).toContain('Poor')
    expect(labelled.text()).toContain('OK')
    expect(labelled.text()).toContain('Great')
    labelled.unmount()
  })
})
