// <auto-generated />
using System;
using Bryk.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bryk.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260726155712_AddActivityFile")]
    partial class AddActivityFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bryk.Domain.Entities.ActivityFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ByteSize")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParsedWorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZoneHistogramJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("ParsedWorkoutId");

                    b.ToTable("ActivityFiles");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("MaxHr")
                        .HasColumnType("int");

                    b.Property<int>("Methodology")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RestingHr")
                        .HasColumnType("int");

                    b.Property<decimal>("TypicalWeeklyHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("YearsTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.AthleteSportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomZonesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Lt1")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("Lt2")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "Sport")
                        .IsUnique();

                    b.ToTable("AthleteSportProfiles");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.AthleteSportZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LowerBound")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UpperBound")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("ZoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "Sport", "ZoneNumber", "Metric")
                        .IsUnique();

                    b.ToTable("AthleteSportZones");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Sport")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomDistanceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("Sport")
                        .HasColumnType("int");

                    b.Property<int?>("TriathlonDistance")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.PlannedWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PlannedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("PlannedLoad")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.HasIndex("AthleteId", "ScheduledDate");

                    b.ToTable("PlannedWorkouts");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BuildWeeks")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Methodology")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("RecoveryWeekPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("RecoveryWeeks")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("EventId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualDistanceMeters")
                        .HasColumnType("int");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvgHr")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ComputedLoad")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LoadOverride")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int?>("MaxHr")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PlannedWorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("PlannedWorkoutId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.WorkoutBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("PlannedWorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Repeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("PlannedWorkoutId", "OrderIndex");

                    b.ToTable("WorkoutBlocks");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.WorkoutStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Intent")
                        .HasColumnType("int");

                    b.Property<decimal?>("LoadKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<int?>("TargetHrHigh")
                        .HasColumnType("int");

                    b.Property<int?>("TargetHrLow")
                        .HasColumnType("int");

                    b.Property<int?>("TargetPaceHigh")
                        .HasColumnType("int");

                    b.Property<int?>("TargetPaceLow")
                        .HasColumnType("int");

                    b.Property<int?>("TargetPowerHigh")
                        .HasColumnType("int");

                    b.Property<int?>("TargetPowerLow")
                        .HasColumnType("int");

                    b.Property<int?>("TargetZone")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkoutBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("WorkoutBlockId", "OrderIndex");

                    b.ToTable("WorkoutSteps");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.WorkoutStepResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualDistanceMeters")
                        .HasColumnType("int");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvgHr")
                        .HasColumnType("int");

                    b.Property<int?>("AvgPace")
                        .HasColumnType("int");

                    b.Property<int?>("AvgPower")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkoutStepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("WorkoutStepId");

                    b.HasIndex("WorkoutId", "OrderIndex");

                    b.ToTable("WorkoutStepResults");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.AthleteSportProfile", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.Athlete", "Athlete")
                        .WithMany("SportProfiles")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.Athlete", "Athlete")
                        .WithMany("Equipment")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Event", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.Athlete", "Athlete")
                        .WithMany("Events")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Goal", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.Athlete", "Athlete")
                        .WithMany("Goals")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.PlannedWorkout", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("PlannedWorkouts")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.TrainingPlan", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.Athlete", "Athlete")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bryk.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.Navigation("Athlete");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Workout", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.PlannedWorkout", "PlannedWorkout")
                        .WithMany()
                        .HasForeignKey("PlannedWorkoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlannedWorkout");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.WorkoutBlock", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.PlannedWorkout", "PlannedWorkout")
                        .WithMany("Blocks")
                        .HasForeignKey("PlannedWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannedWorkout");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.WorkoutStep", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.WorkoutBlock", "WorkoutBlock")
                        .WithMany("Steps")
                        .HasForeignKey("WorkoutBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutBlock");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.WorkoutStepResult", b =>
                {
                    b.HasOne("Bryk.Domain.Entities.Workout", "Workout")
                        .WithMany("StepResults")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bryk.Domain.Entities.WorkoutStep", null)
                        .WithMany()
                        .HasForeignKey("WorkoutStepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Athlete", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Events");

                    b.Navigation("Goals");

                    b.Navigation("SportProfiles");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.PlannedWorkout", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.TrainingPlan", b =>
                {
                    b.Navigation("PlannedWorkouts");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.Workout", b =>
                {
                    b.Navigation("StepResults");
                });

            modelBuilder.Entity("Bryk.Domain.Entities.WorkoutBlock", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
